# Generated by Django 5.2.7 on 2025-10-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='promo_system_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='services_for_promo',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
