# Generated by Django 5.2.8 on 2025-11-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashregister',
            name='opening_amount',
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='closing_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='initial_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
