# Generated by Django 5.2.8 on 2025-12-01 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_cashregister_initial_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='business_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterUniqueTogether(
            name='cashregister',
            unique_together={('business_date', 'is_open')},
        ),
    ]
