# Generated by Django 5.2.8 on 2025-12-02 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_cashregister_business_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='business_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
