# Generated by Django 5.2.8 on 2025-12-04 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_cashregister_business_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashregister',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_opened', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='cashregister',
            constraint=models.UniqueConstraint(condition=models.Q(('is_open', True)), fields=('business_date',), name='unique_open_cash_per_day'),
        ),
    ]
