# Generated by Django 5.2.7 on 2025-11-01 21:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('specialties', models.CharField(help_text='Ej: Uñas acrílicas, Gelish, Decorado, etc.', max_length=255)),
                ('working_days', models.CharField(help_text='Ej: Lunes a Sábado', max_length=100)),
                ('start_time', models.TimeField(default='10:00')),
                ('end_time', models.TimeField(default='18:00')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
