# Generated by Django 5.2.8 on 2025-12-06 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_manos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_manos', to='appointments.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_pies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_pies', to='appointments.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('manos', 'Manos'), ('pies', 'Pies')], default='manos', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='duration_hours',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4),
        ),
    ]
