# Generated by Django 5.2.8 on 2025-12-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
