# Generated by Django 5.2.8 on 2025-12-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_duration_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='requires_deposit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pendiente de pago'), ('scheduled', 'Agendada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20),
        ),
    ]
