# Generated by Django 5.2.8 on 2025-12-01 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_cashregister_business_date_and_more'),
        ('sales', '0002_sale_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='billing.cashregister'),
        ),
    ]
